### ISSUE TITLE
Getting the following error? Unsure if I fucked up something or what?

### ISSUE THREAD

**Issue by MLGMagicHoodini** [Xientraa/The-Sims-Resource-Downloader#14]
Traceback (most recent call last):
  File "G:\Users\saped\Desktop\The-Sims-Resource-Downloader-0.4.1\src\main.py", line 2, in <module>
    from TSRUrl import TSRUrl
  File "G:\Users\saped\Desktop\The-Sims-Resource-Downloader-0.4.1\src\TSRUrl.py", line 3, in <module>
    from logger import logger
  File "G:\Users\saped\Desktop\The-Sims-Resource-Downloader-0.4.1\src\logger.py", line 4, in <module>
    from config import CONFIG
  File "G:\Users\saped\Desktop\The-Sims-Resource-Downloader-0.4.1\src\config.py", line 13, in <module>
    CONFIG: CONFIG_DICT = json.load(open(CURRENT_DIR + "/config.json", "r"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 29 (char 30)

**Comment by mgjlopez** [comment]
Make sure you are escaping the '\' in the **downloadDirectory** path in the 'config.json' file.

For example, you should use '**C:\\user\\downloads**' instead of just '**C:\user\downloads**'

**Comment by MLGMagicHoodini** [comment]
> Make sure you are escaping the '`\`' in the **downloadDirectory** path in the 'config.json' file.
> 
> For example, you should use '`C:\\user\\downloads`' instead of just '`C:\user\downloads`'

After checking other issues, and fixing the errors on my part, I managed get it working, just missed some stuff that wasn't told in the Instalation/Usage part, but thanks for the help
